project:
  type: website
  output-dir: docs

website:
  title: "Muhammad Ahmad Sajid"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - projects.qmd
      - about.qmd
    tools:
      - icon: github
        href: https://github.com/MuhammadAhmadSajid

format:
  html:
    theme: cosmo
    css: styles.css