project:
  type: website
  output-dir: docs

website:
  title: "Muhammad Ahmad Sajid"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Projects"
        file: projects.qmd
      - text: "About me"
        file: about.qmd
    tools:
      - icon: github
        href: https://github.com/MuhammadAhmadSajid
      - icon: linkedin
        href: https://linkedin.com

format:
  html:
    theme: cosmo
    css: styles.css
    fontsize: 1.1em